/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

const (
	CimMountFlagNone         uint32 = 0x0
	CimMountFlagChildOnly    uint32 = 0x1
	CimMountFlagEnableDax    uint32 = 0x2
	CimMountFlagCacheFiles   uint32 = 0x4
	CimMountFlagCacheRegions uint32 = 0x8
	CimMountBlockDeviceCim   uint32 = 0x10
	CimMountSingleFileCim    uint32 = 0x20

	CimCreateFlagNone                uint32 = 0x0
	CimCreateFlagDoNotExpandPEImages uint32 = 0x1
	CimCreateFlagFixedSizeChunks     uint32 = 0x2
	CimCreateFlagBlockDeviceCim      uint32 = 0x4
	CimCreateFlagSingleFileCim       uint32 = 0x8

	CimMergeFlagNone        uint32 = 0x0
	CimMergeFlagSingleFile  uint32 = 0x1
	CimMergeFlagBlockDevice uint32 = 0x2

	CimReadFileFlagNone          uint32 = 0x0
	CimReadFileFlagSingleFileCIM uint32 = 0x1

	CimStatFileFlagNone          uint32 = 0x0
	CimStatFileFlagSingleFileCIM uint32 = 0x1
)

type CimMount struct {
	ImagePath      string `json:"ImagePath,omitempty"`
	FileSystemName string `json:"FileSystemName,omitempty"`
	VolumeGuid     string `json:"VolumeGuid,omitempty"`
	MountFlags     uint32 `json:"MountFlags,omitempty"`
}
