/*
 * HCS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

import "github.com/Microsoft/go-winio/pkg/guid"

type Layer struct {
	Id string `json:"Id,omitempty"`

	Path string `json:"Path,omitempty"`

	PathType string `json:"PathType,omitempty"`

	//  Unspecified defaults to Enabled
	Cache string `json:"Cache,omitempty"`
}

type OsLayerType string

const (
	ContainerLayer OsLayerType = "Container"
	VmLayer                    = "Vm"
)

type OsLayerOptions struct {
	Type_ OsLayerType `json:"Type,omitempty"`

	DisableCiCacheOptimization bool `json:"DisableCiCacheOptimization,omitempty"`

	IsDynamic bool `json:"IsDynamic,omitempty"`

	SkipSandboxPreExpansion bool `json:"SkipSandboxPreExpansion,omitempty"`

	FileSystemLayers []Layer `json:"FileSystemLayers,omitempty"`

	SandboxVhdPartitionId guid.GUID `json:"SandboxVhdPartitionId,omitempty"`

	SkipUpdateBcdForBoot bool `json:"SkipUpdateBcdForBoot,omitempty"`
}
